export const OPEN_CREATE_ORGANIZATION = "OPEN_CREATE_ORGANIZATION"
export const CLOSE_CREATE_ORGANIZATION = "CLOSE_CREATE_ORGANIZATION"


export const OPEN_MOBILE_TOGGLE = "OPEN_MOBILE_TOGGLE"
export const CLOSE_MOBILE_TOGGLE = "CLOSE_MOBILE_TOGGLE"

export const OPEN_ORG_SETTING = "OPEN_ORG_SETTING"
export const CLOSE_ORG_SETTING = "CLOSE_ORG_SETTING"

export const OPEN_MEMBER_SETTING = "OPEN_MEMBER_SETTING"
export const CLOSE_MEMBER_SETTING = "CLOSE_MEMBER_SETTING"

export const OPEN_CREATE_BOARD = "OPEN_CREATE_BOARD"
export const CLOSE_CREATE_BOARD = "CLOSE_CREATE_BOARD"


export const OPEN_CARD_DETAIL = "OPEN_CARD_DETAIL"
export const CLOSE_CARD_DETAIL = "CLOSE_CARD_DETAIL"


export const GET_CARD_REQUEST = "GET_CARD_REQUEST"
export const GET_CARD_SUCCESS = "GET_CARD_SUCCESS"
export const GET_CARD_FAIL = "GET_CARD_FAIL"